# Generated by Django 3.2.9 on 2021-11-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
