# Generated by Django 3.2.9 on 2021-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_holder',
        ),
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='job_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
