# Generated by Django 3.2.7 on 2021-12-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0008_user_workexperiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='workExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_startingDate', models.DateField(blank=True, null=True)),
                ('experience_endDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='workExperiences',
        ),
    ]
