# Generated by Django 3.2.7 on 2021-12-27 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0009_auto_20211228_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.user'),
            preserve_default=False,
        ),
    ]
