# Generated by Django 3.2.7 on 2021-12-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0010_workexperiences_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperiences',
            old_name='user',
            new_name='graduateUser',
        ),
    ]
