# Generated by Django 3.2.7 on 2021-12-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_auto_20211228_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiences',
            name='graduateUser',
        ),
    ]
