# Generated by Django 3.2.7 on 2021-12-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0013_remove_workexperiences_graduateuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workExperiences',
        ),
    ]
