# Generated by Django 3.2.7 on 2021-12-28 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0014_delete_workexperiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='workExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('experienceStartDate', models.DateField(blank=True, null=True)),
                ('experienceEndDate', models.DateField(blank=True, null=True)),
                ('graduateUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
