# Generated by Django 3.2.7 on 2022-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0015_workexperiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiences',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
