# Generated by Django 3.2.7 on 2022-02-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0017_alter_workexperiences_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employmentstat',
            new_name='employment_status',
        ),
    ]
