# Generated by Django 3.2.7 on 2022-02-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0019_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
