# Generated by Django 3.2.7 on 2022-02-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0020_delete_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
