# Generated by Django 3.2.7 on 2022-02-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0022_auto_20220217_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
