# Generated by Django 3.2.7 on 2022-02-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0023_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
