# Generated by Django 3.2.7 on 2022-02-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0024_auto_20220217_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
