# Generated by Django 3.2.7 on 2022-02-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0025_auto_20220217_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/img')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('announcement_notif_counter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('job_category_notif_counter', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='coursegraduated',
            old_name='bit_grad',
            new_name='bit',
        ),
        migrations.RenameField(
            model_name='coursegraduated',
            old_name='bsit_grad',
            new_name='bsit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adminApprover',
            new_name='admin_approver',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bit_grad',
            new_name='bit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bsit_grad',
            new_name='bsit',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contactnum',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='year_graduated',
            new_name='date_graduated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employedGrad',
            new_name='employed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='unemployedGrad',
            new_name='unemployed',
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('total_vote', models.IntegerField(default=0, editable=False)),
                ('job_request_notif_counter', models.BooleanField(default=False)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracer.jobcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.jobcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('total_vote', models.IntegerField(default=0, editable=False)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracer.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address_1', models.CharField(max_length=50, null=True)),
                ('address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email_address', models.CharField(max_length=50, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement/img')),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_sent', models.BooleanField(default=False)),
                ('job_advertise_notif_counter', models.BooleanField(default=False)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracer.jobcategory')),
            ],
        ),
    ]
