# Generated by Django 3.2.7 on 2022-02-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0026_auto_20220218_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
