# Generated by Django 4.1 on 2022-08-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0028_auto_20220323_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_graduated',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=100, null=True),
        ),
    ]
