# Generated by Django 4.1 on 2022-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0029_alter_user_contact_number_alter_user_date_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IDNum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
