# Generated by Django 4.0.5 on 2022-09-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0033_alter_schoolgraduated_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolgraduated',
            old_name='campus',
            new_name='name',
        ),
    ]
