# Generated by Django 4.0.5 on 2022-09-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0035_remove_user_argao_campus_remove_user_barili_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=100, null=True)),
                ('employed', models.BooleanField(default=False)),
                ('unemployed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unemployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracer.graduatestatus'),
        ),
    ]
