# Generated by Django 4.1.1 on 2022-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0036_graduatestatus_user_employed_user_unemployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approver_admin',
            field=models.BooleanField(default=False),
        ),
    ]
