# Generated by Django 4.1.1 on 2022-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0037_user_approver_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('graduate', 'graduate'), ('admin_approver', 'admin_approver'), ('approver_admin', 'approver_admin')], max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin_approver',
            new_name='admin_sao',
        ),
    ]
