# Generated by Django 4.1.1 on 2022-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0040_alter_user_school_delete_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GraduateStatus',
        ),
    ]
