# Generated by Django 4.1.1 on 2022-09-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0041_alter_user_employment_status_delete_graduatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AdminSao', 'AdminSao'), ('AdminAppprover', 'AdminAppprover')], max_length=100, null=True),
        ),
    ]
