# Generated by Django 4.1.1 on 2022-09-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0043_rename_approver_admin_user_system_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('userid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.BinaryField(max_length=450)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(default='', max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('emailaddress', models.EmailField(max_length=254, null=True)),
                ('usertype', models.CharField(max_length=45)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_2.png', null=True, upload_to='')),
                ('approver_flag', models.CharField(default='0', max_length=50)),
            ],
            options={
                'db_table': 'systemuser',
            },
        ),
        migrations.AlterModelTable(
            name='advertise',
            table='advertise',
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
        migrations.AlterModelTable(
            name='categorytype',
            table='categorytype',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='controlvote',
            table='controlvote',
        ),
        migrations.AlterModelTable(
            name='jobcategory',
            table='jobcategory',
        ),
        migrations.AlterModelTable(
            name='jobrequest',
            table='jobrequest',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='workexperiences',
            table='workexperiences',
        ),
    ]
