# Generated by Django 4.1.1 on 2022-09-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0045_alter_advertise_id_alter_announcement_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='graduate',
        ),
    ]
