# Generated by Django 4.1.1 on 2022-09-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0046_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
