# Generated by Django 4.1.1 on 2022-09-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0050_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
