# Generated by Django 4.1.1 on 2022-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0051_delete_systemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('userid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.BinaryField(max_length=450)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(default='', max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('emailaddress', models.EmailField(max_length=254, null=True)),
                ('usertype', models.CharField(max_length=45)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_2.png', null=True, upload_to='')),
                ('approver_flag', models.CharField(default='0', max_length=50)),
            ],
            options={
                'db_table': 'systemuser',
            },
        ),
    ]
