# Generated by Django 4.1.1 on 2022-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0052_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='graduate',
            new_name='campus_director',
        ),
        migrations.AddField(
            model_name='user',
            name='dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='university_pres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AdminSao', 'AdminSao'), ('SystemAdmin', 'SystemAdmin'), ('DEAN', 'DEAN'), ('Campus Director', 'Campus Director'), ('University President', 'University President')], max_length=100, null=True),
        ),
    ]
