# Generated by Django 4.1.1 on 2022-09-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0055_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
