# Generated by Django 4.1.1 on 2022-09-28 20:44

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tracer', '0056_delete_systemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.BinaryField(blank=True, max_length=450)),
                ('first_name', models.CharField(blank=True, max_length=45)),
                ('middle_name', models.CharField(blank=True, max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45)),
                ('school', models.CharField(blank=True, choices=[('Argao Campus', 'Argao Campus'), ('Barili Campus', 'Barili Campus'), ('Carmen Campus', 'Carmen Campus'), ('Cebu City Mountain Extension Campus', 'Cebu City Mountain Extension Campus'), ('Daanbantayan Campus', 'Daanbantayan Campus'), ('Danao Campus', 'Danao Campus'), ('Dumanjug Extension Campus', 'Dumanjug Extension Campus'), ('Ginatilan Extension Campus', 'Ginatilan Extension Campus'), ('Main Campus', 'Main Campus'), ('Moalboal Campus', 'Moalboal Campus'), ('Naga Extension Campus', 'Naga Extension Campus'), ('Oslob Extension Campus', 'Oslob Extension Campus'), ('Pinamungajan Extension Campus', 'Pinamungajan Extension Campus'), ('San Fernando Extension Campus', 'San Fernando Extension Campus'), ('San Francisco Campus', 'San Francisco Campus'), ('Tuburan Campus', 'Tuburan Campus')], max_length=100, null=True)),
                ('argaoCampus', models.BooleanField(default=False)),
                ('bariliCampus', models.BooleanField(default=False)),
                ('carmenCampus', models.BooleanField(default=False)),
                ('CCMECampus', models.BooleanField(default=False)),
                ('daanbantayanCampus', models.BooleanField(default=False)),
                ('danaoCampus', models.BooleanField(default=False)),
                ('dumanjugExt', models.BooleanField(default=False)),
                ('ginatilanExt', models.BooleanField(default=False)),
                ('mainCampus', models.BooleanField(default=False)),
                ('moalboalCampus', models.BooleanField(default=False)),
                ('nagaExt', models.BooleanField(default=False)),
                ('oslobExt', models.BooleanField(default=False)),
                ('pinamungajanExt', models.BooleanField(default=False)),
                ('sanfernandoExt', models.BooleanField(default=False)),
                ('sanfranciscoCampus', models.BooleanField(default=False)),
                ('tuburanCampus', models.BooleanField(default=False)),
                ('user_type', models.CharField(blank=True, choices=[('AdminSao', 'AdminSao'), ('SystemAdmin', 'SystemAdmin'), ('DEAN', 'DEAN'), ('Campus Director', 'Campus Director'), ('University President', 'University President')], max_length=100, null=True)),
                ('admin_sao', models.BooleanField(default=False)),
                ('system_admin', models.BooleanField(default=False)),
                ('dean', models.BooleanField(default=False)),
                ('campus_director', models.BooleanField(default=False)),
                ('university_pres', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='default_profile_2.png', null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'systemuser',
            },
        ),
    ]
