# Generated by Django 4.1.1 on 2022-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0058_remove_systemuser_admin_remove_systemuser_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='systemuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
