# Generated by Django 4.1.1 on 2022-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0059_remove_systemuser_is_staff_systemuser_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
