# Generated by Django 4.1.1 on 2022-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0061_alter_systemuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiences',
            name='description',
        ),
        migrations.AddField(
            model_name='workexperiences',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
