# Generated by Django 4.1.1 on 2022-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0062_remove_workexperiences_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
