# Generated by Django 4.1.1 on 2022-10-13 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0063_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
