# Generated by Django 4.0.5 on 2022-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0065_alter_announcement_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='job_sent_list',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
