# Generated by Django 4.0.5 on 2022-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0067_remove_advertise_job_sent_list_user_job_sent_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_sent_list',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
